version: "3.2"
services:
  # db:
  #   restart: always
  #   image: mariadb:5.5
  #   environment:
  #     - MYSQL_HOST=localhost
  #     - MYSQL_PORT=3306
  #     - MYSQL_ROOT_HOST=%
  #     - MYSQL_DATABASE=bug
  #     - MYSQL_USER=<<username>>
  #     - MYSQL_PASSWORD=<<password>>
  #     - MYSQL_ROOT_PASSWORD=<<rootpassword>>
  #   ports:
  #     - "3302:3306"
  #   networks:
  #     - db-net
  db:
    image: postgres
    restart: always
    container_name: db
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - db-net

  backend:
    restart: always
    container_name: backend
    # env_file:
      # - ./backend/settings.ini
    build:
      context: ./backend/
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app/backend
    depends_on:
      - db
    networks:
      - db-net

  frontend:
    restart: always
    container_name: frontend
    command : "npm run dev"
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    ports:
      - 2137:2137
    stdin_open: true
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    depends_on:
      - backend

networks:
  db-net:
    driver: bridge

volumes:
  pgdata:
